import type { AiDifficultyPreset } from '@/ai/types';

/** Exact product difficulty presets used by the browser worker and the tests. */
export const AI_DIFFICULTY_PRESETS: Record<'easy' | 'medium' | 'hard', AiDifficultyPreset> = {
  easy: {
    familyVarietyWeight: 30,
    frontierWidthWeight: 20,
    timeBudgetMs: 120,
    maxDepth: 2,
    participationBias: 14,
    participationWindow: 2,
    policyPriorWeight: 80,
    quietMoveLimit: 8,
    repetitionPenalty: 120,
    selfUndoPenalty: 220,
    rootCandidateLimit: 4,
    sourceReusePenalty: 70,
    varietyTemperature: 0.35,
    varietyThreshold: 0.08,
    varietyTopCount: 3,
  },
  medium: {
    familyVarietyWeight: 42,
    frontierWidthWeight: 28,
    timeBudgetMs: 400,
    maxDepth: 4,
    participationBias: 18,
    participationWindow: 3,
    policyPriorWeight: 140,
    quietMoveLimit: 16,
    repetitionPenalty: 180,
    selfUndoPenalty: 320,
    rootCandidateLimit: 5,
    sourceReusePenalty: 100,
    varietyTemperature: 0.22,
    varietyThreshold: 0.03,
    varietyTopCount: 2,
  },
  hard: {
    familyVarietyWeight: 56,
    frontierWidthWeight: 36,
    timeBudgetMs: 1200,
    maxDepth: 6,
    participationBias: 24,
    participationWindow: 3,
    policyPriorWeight: 220,
    quietMoveLimit: 28,
    repetitionPenalty: 240,
    selfUndoPenalty: 420,
    rootCandidateLimit: 6,
    sourceReusePenalty: 140,
    varietyTemperature: 0.15,
    varietyThreshold: 0.015,
    varietyTopCount: 3,
  },
};
