import { hashPosition } from '@/domain';
import type { GameState } from '@/domain/model/types';

import {
  createLateGamePerfState,
  createRandomPlayPerfState,
} from './lateGamePerfFixtures';

export type AiScenarioBucket =
  | 'opening'
  | 'realisticEarly'
  | 'realisticMidgame'
  | 'realisticLate'
  | 'congested'
  | 'loopPressure'
  | 'conversionRace'
  | 'lateSparse';

export type AiScenarioDefinition = {
  bucket: AiScenarioBucket;
  label: string;
  /** Stable assignment for strength experiments. Keep this explicit so inserting or
   * reordering behavior-report scenarios cannot leak a holdout into development. */
  strengthSplit: 'development' | 'holdout';
  turnCount: number;
  /** When true the position is generated by seeded random legal-move play instead
   *  of the fixed PREFIX_17 + LOOP_CYCLE trace. */
  randomPlay?: true;
  seed?: number;
};

const RETAINED_HISTORY_WINDOW = 6;

export const POSITION_BUCKET_SCENARIOS: AiScenarioDefinition[] = [
  {
    bucket: 'opening',
    label: 'opening',
    strengthSplit: 'development',
    turnCount: 0,
  },
  // Realistic mid-game positions: all pieces still active, typical branching factor.
  {
    bucket: 'realisticMidgame',
    label: 'midgame20',
    strengthSplit: 'holdout',
    turnCount: 20,
    randomPlay: true,
    seed: 0x1a2b3c,
  },
  {
    bucket: 'realisticMidgame',
    label: 'midgame40',
    strengthSplit: 'development',
    turnCount: 40,
    randomPlay: true,
    seed: 0x4d5e6f,
  },
  // Loop-trace positions: useful for loop-pressure and draw-aversion metrics.
  {
    bucket: 'congested',
    label: 'turn25',
    strengthSplit: 'development',
    turnCount: 25,
  },
  {
    bucket: 'loopPressure',
    label: 'turn50',
    strengthSplit: 'holdout',
    turnCount: 50,
  },
  {
    bucket: 'loopPressure',
    label: 'turn75',
    strengthSplit: 'development',
    turnCount: 75,
  },
  {
    bucket: 'conversionRace',
    label: 'turn100',
    strengthSplit: 'development',
    turnCount: 100,
  },
  {
    bucket: 'conversionRace',
    label: 'turn150',
    strengthSplit: 'holdout',
    turnCount: 150,
  },
  {
    bucket: 'lateSparse',
    label: 'turn200',
    strengthSplit: 'development',
    turnCount: 200,
  },
  // Independent seeded legal-play traces broaden the portfolio beyond the synthetic
  // loop fixture. Holdout membership is balanced across early, middle, and late play.
  {
    bucket: 'realisticEarly',
    label: 'random10a',
    strengthSplit: 'development',
    turnCount: 10,
    randomPlay: true,
    seed: 0x7f4a7c,
  },
  {
    bucket: 'realisticEarly',
    label: 'random10b',
    strengthSplit: 'holdout',
    turnCount: 10,
    randomPlay: true,
    seed: 0x9e3779,
  },
  {
    bucket: 'realisticMidgame',
    label: 'random30a',
    strengthSplit: 'development',
    turnCount: 30,
    randomPlay: true,
    seed: 0xb5297a,
  },
  {
    bucket: 'realisticMidgame',
    label: 'random40a',
    strengthSplit: 'development',
    turnCount: 40,
    randomPlay: true,
    seed: 0x68e31d,
  },
  {
    bucket: 'realisticMidgame',
    label: 'random50a',
    strengthSplit: 'holdout',
    turnCount: 50,
    randomPlay: true,
    seed: 0x1b56c4,
  },
  {
    bucket: 'realisticLate',
    label: 'random60a',
    strengthSplit: 'development',
    turnCount: 60,
    randomPlay: true,
    seed: 0xc2b2ae,
  },
  {
    bucket: 'realisticLate',
    label: 'random75a',
    strengthSplit: 'development',
    turnCount: 75,
    randomPlay: true,
    seed: 0x7f4a7c,
  },
  {
    bucket: 'realisticLate',
    label: 'random75b',
    strengthSplit: 'holdout',
    turnCount: 75,
    randomPlay: true,
    seed: 0x9e3779,
  },
  {
    bucket: 'realisticLate',
    label: 'random90a',
    strengthSplit: 'development',
    turnCount: 90,
    randomPlay: true,
    seed: 0xb5297a,
  },
] as const;

/**
 * The perf traces are replayed with draw resolution disabled so they stay reachable.
 * For behavior reports we keep only the recent history window and rebuild repetition
 * counts from that window, which makes the imported late positions playable without
 * smuggling a terminal threefold state into the continuation harness.
 */
export function createContinuationScenarioState(state: GameState): GameState {
  const retainedHistory = state.history.slice(-RETAINED_HISTORY_WINDOW);
  const rebuiltPositionCounts: Record<string, number> = {};

  if (retainedHistory.length) {
    const firstBeforeHash = hashPosition(retainedHistory[0].beforeState);
    rebuiltPositionCounts[firstBeforeHash] = 1;

    for (const record of retainedHistory) {
      const afterHash = hashPosition(record.afterState);
      rebuiltPositionCounts[afterHash] =
        (rebuiltPositionCounts[afterHash] ?? 0) + 1;
    }
  } else {
    rebuiltPositionCounts[hashPosition(state)] = 1;
  }

  return {
    ...state,
    history: retainedHistory,
    positionCounts: rebuiltPositionCounts,
    status: 'active',
    victory: { type: 'none' },
  };
}

export function buildScenarioState(
  scenario: AiScenarioDefinition,
  ruleConfig: Parameters<typeof createLateGamePerfState>[1],
): GameState {
  if (scenario.randomPlay) {
    // Random-play positions don't have accumulated position-count history that
    // would trigger threefold, so no need for createContinuationScenarioState.
    return createRandomPlayPerfState(
      scenario.turnCount,
      ruleConfig,
      scenario.seed,
    );
  }

  if (scenario.turnCount === 0) {
    return createLateGamePerfState(0, ruleConfig);
  }

  // Long benchmark traces intentionally contain repeated cycles. Replay them
  // without terminating on the measurement draw rule, then rebuild a valid
  // continuation state with bounded, internally consistent history/counts.
  return createContinuationScenarioState(
    createLateGamePerfState(scenario.turnCount, {
      ...ruleConfig,
      drawRule: 'none',
    }),
  );
}
